verifyDepsBeforeRun: install
minimumReleaseAgeExclude:
  - "@oxc-parser/*"
  - "@oxc-project/*"
  - "@oxfmt/*"
  - "@oxlint-tsgolint/*"
  - "@oxlint/*"
  - "@rolldown/*"
  - "@tsdown/*"
  - "@vitejs/devtools"
  - "@vitest/*"
  - "@voidzero-dev/*"
  - oxc-parser
  - oxfmt
  - oxlint
  - oxlint-tsgolint
  - rolldown
  - tsdown
  - vite
  - vite-plus
  - vitest
allowBuilds:
  better-sqlite3: false
  esbuild: false
  sharp: false
  vue-demi: false
  workerd: false
overrides:
  esbuild: 0.28.0
packages:
