name: Update Linter Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 */2 * *" # Every other day at 18:00 UTC.

permissions: {}

jobs:
  update-linter-rules:
    name: Update linter rules
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: oxc-project/setup-node@4c26e7cb3605b6bdef5450dacd02c434b10fd8ba # v1.2.0

      - run: pnpm install --frozen-lockfile

      - run: pnpm run generate:linter-rules

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: Regenerate linter rules
          title: Regenerate linter rules
          body: |
            Automated update of `src/generated/linter-rules.json` from the
            [website repo](https://github.com/oxc-project/website/blob/main/.vitepress/data/rules.json).
          branch: update-linter-rules
          delete-branch: true
